#site structure
menus:
 - title: News
   items: [{ id: news , url: /news , name: Current News  }]
 - title: Works
   items:
    - { id: photography , url: /photography , name: Photography }
    - {id: editions, name: Editions, url: /editions/ }
    - {id: videos , url: /videos/ , name: Videos }
 - title: Biography
   items:
    - { id: exhibitions , name: Exhibitions , url: /exhibitions/ }
    - { id: bibliography , name: Bibliography ,url: /bibliography/ }
 - title: Extras
   items:
    # - {id: wallpapers , name: Wallpapers , url: /wallpapers/}
    - {id: links , url: /links/, name: Links}
    - {id: contact , url: /contact/ , name: Contact}
    - {id: guestbook , url: /guestbook/ , name: Guestbook}

pages: 
 news:
  title: Welcome
  keywords: Elina Brotherus, photography, Finnish photography, Elina Brotherus website, Elina Brotherys, valokuvaus,  elinabrotherus.com</
  desc: Welcome to elinabrotherus.com. Elina Brotherus is a Finnish photographer currently living in France.
 photography:
  title: Photography
  keywords: Elina Brotherus, pictures, photographs, Elina Brotherus photo series
  desc: elinabrotherus.com - Photography series 
 editions:
  title: Editions
  keywords: Elina Brotherus, editions,The New Painting ,Complete Videoworks
  desc: inabrotherus.com - Editions
 bibliography:
  title: Bibliography
  keywords: Bibliography,Elina Brotherus,Articles,Interview,Bibliography
  desc: elinabrotherus.com - Articles, Interviews and Bibliography.
 exhibitions:
  title: Exhibitions
  keywords: exibitions, Elina Brotherus,Ecology of Emotions,Correspondences ,  Martin Asbaek Gallery, Myth of Childhood , La Ruche en d’autres thèrmes
  desc: elinabrotherus.com - Exhibitions
 videos: 
  title: Videos Works
  keywords: Elina Brotherus, video works, videos
  desc: elinabrotherus.com - Video works
 links:
  title: Links
  keywords: links from elinabrotherus
  desc: Links to people and things I support
 contact:
  title: Send me a message
  keywords: www.elinabrotherus.com
  desc: the crew
 guestbook:
  title: Guestbook
  keywords: guestbook
  desc: Guestbook for elinabrotherus.com